version: "3"
services:
  deeplearning:
    image: "jwatson/thesis_env12:latest"
    volumes:
      - "nfsnasmount:/NAS/"
      - "clean_dataset:/clean_nvme/"
    ports:
      - "3030:22"
    environment:
      NVIDIA_VISIBLE_DEVICES: 0,1

volumes:
  nfsnasmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.202.0.11
      device: ":/volume1/homes/jwatson/"
  clean_dataset:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.202.0.11
      device: ":/volume1/homes/jwatson/clean_dataset"