TEST=scale_test_4
REMOTE_IP=10.202.0.12
# LAST_EPOCH=200

LOCAL_USER=jwatson27
LOCAL_HOME=/home/$LOCAL_USER
LOCAL_PROJ=$LOCAL_HOME/PycharmProjects/Thesis_VO

REMOTE_USER=jwatson
REMOTE_HOME=/home/$REMOTE_USER
REMOTE_LOGIN=$REMOTE_USER@$REMOTE_IP

TRAINING_DIR=training/$TEST
EPOCHS_DIR=$TRAINING_DIR/training_epochs

#mkdir $LOCAL_HOME/thesis/$TRAINING_DIR
#scp -r $REMOTE_LOGIN:$REMOTE_HOME/$TRAINING_DIR/history $LOCAL_HOME/thesis/$TRAINING_DIR
#scp -r $REMOTE_LOGIN:$REMOTE_HOME/$TRAINING_DIR/model $LOCAL_HOME/thesis/$TRAINING_DIR

mkdir $LOCAL_HOME/thesis/$EPOCHS_DIR
scp -r $REMOTE_LOGIN:$REMOTE_HOME/$EPOCHS_DIR/epoch_*.h5 $LOCAL_HOME/thesis/$EPOCHS_DIR

#BEST_EPOCH=168
#scp -r $REMOTE_LOGIN:$REMOTE_HOME/$EPOCHS_DIR/epoch_$BEST_EPOCH.h5 $LOCAL_HOME/thesis/$EPOCHS_DIR