#   Defines paths for datasets and save locations
# and general parameters and consistent values
pathsGeneral:
  trainRoot: &train_root '/opt/project/training'
  resultsRoot: &results_root '/opt/project/results'
  windowsRoot: &windows_root '/windowsroot'
  cleanDataset: &clean_dataset '/clean_dataset'


resultPaths:
  figures:
    dir: !!python/object/apply:os.path.join [*results_root, 'figures']
  evaluations:
    dir: !!python/object/apply:os.path.join [*results_root, 'evals']


datasets:
  kitti:
    parameters:
      sampleRate: 10 # Hz
      splitFractions: [0.65, 0.2, 0.15]
      turnThreshold: 1 # deg
      standardImageShape: !!python/tuple [370, 1226]
      downsampledImageShape: !!python/tuple [320, 1216]
      normPixelRange: [0, 1]

    paths:
      general:
        kittiRoot: &kitti_root !!python/object/apply:os.path.join [*windows_root, 'Pictures/Kitti_Odometry']
        kittiOrigTruth: &kitti_orig_truth !!python/object/apply:os.path.join [*kitti_root, 'data_odometry_poses/dataset/poses']
        kittiOrigGray: &kitti_orig_gray !!python/object/apply:os.path.join [*kitti_root, 'data_odometry_gray/dataset/sequences']
        kittiOrigColor: &kitti_orig_color !!python/object/apply:os.path.join [*kitti_root, 'data_odometry_color/dataset/sequences']
        kittiPrep: &kitti_prep !!python/object/apply:os.path.join [*clean_dataset, 'kitti_odom']
        kittiNorm: &kitti_norm !!python/object/apply:os.path.join [*clean_dataset, 'kitti_norm']
        kittiOrigCameras: &orig_cams ['image_0', 'image_1', 'image_2', 'image_3']
        kittiSeqs: &seqs ['00', '01', '02', '03', '04', '05', '06', '07', '08', '09', '10']
        cameras: &new_cams ['cam_0', 'cam_1', 'cam_2', 'cam_3']



      original:
        truth:
          dir: [*kitti_orig_truth]
          type: '.txt'
        images:
          cal:
            dir: [*kitti_orig_gray, *seqs]
            name: 'calib.txt'
          cams:
            dir: [*kitti_orig_gray, *seqs, *orig_cams]
            type: '.png'

      prepared:
        split:
          dir: [*kitti_prep]
          name: 'split_idxs.hdf5'
        truth:
          dir: [*kitti_prep, *seqs]
          name: 'truth.hdf5'
        standardImages:
          dir: [*kitti_prep, *seqs, *new_cams, 'standardized']
          type: '.png'
        imu:
          dir: [*kitti_prep, *seqs]
          name: 'imu.hdf5'
        epipolar:
          dir: [*kitti_prep, *seqs, *new_cams]
          name: 'epipolar.hdf5'

      normalized:
        normImages:
          dir: [*kitti_norm, *seqs, *new_cams, 'normalized']
          type: '.hdf5'
        normData:
          dir: [*kitti_norm, 'normalized']
          name: 'norm_data.hdf5'



